[package]
name = "rust-greenhouse"
version = "0.1.0"
authors = ["Sascha Koch <koch@smartsquare.de>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
